import { HandImage } from './handImages';

const IMAGEPATH = 'img/small/';

export var EXISTINGIMAGES: HandImage[] = [
  { id: 1, name: 'Bild1', side: 'left', path: IMAGEPATH+'img7.png'},
  { id: 2, name: 'Bild2', side: 'right', path: IMAGEPATH+'img2.png'},
  { id: 3, name: 'Bild3', side: 'right', path: IMAGEPATH+'img3.png'},
  { id: 4, name: 'Bild4', side: 'left', path:  IMAGEPATH+'img8.png'},
  { id: 5, name: 'Bild5', side: 'right', path: IMAGEPATH+'img15.png'},
  { id: 6, name: 'Bild6', side: 'left', path: IMAGEPATH+'img17.png'},
  { id: 7, name: 'Bild7', side: 'right', path: IMAGEPATH+'img19.png'},
  { id: 8, name: 'Bild8', side: 'right', path: IMAGEPATH+'img6.png'},
  { id: 9, name: 'Bild9', side: 'left', path: IMAGEPATH+'img16.png'},
  { id: 10, name: 'Bild10', side: 'right', path: IMAGEPATH+'img4.png'},
  { id: 11, name: 'Bild11', side: 'right', path: IMAGEPATH+'img18.png'},
  { id: 12, name: 'Bild12', side: 'right', path: IMAGEPATH+'img9.png'},
  { id: 13, name: 'Bild13', side: 'left', path: IMAGEPATH+'img13.png'},
  { id: 14, name: 'Bild14', side: 'right', path: IMAGEPATH+'img14.png'},
  { id: 15, name: 'Bild15', side: 'right', path: IMAGEPATH+'img5.png'},
  { id: 16, name: 'Bild16', side: 'left', path: IMAGEPATH+'img20.png'},
  { id: 17, name: 'Bild17', side: 'right', path: IMAGEPATH+'img10.png'},
  { id: 18, name: 'Bild18', side: 'left', path: IMAGEPATH+'img21.png'},
  { id: 19, name: 'Bild19', side: 'right', path: IMAGEPATH+'img12.png'},
  { id: 20, name: 'Bild20', side: 'right', path: IMAGEPATH+'img11.png'},
  { id: 21, name: 'Bild21', side: 'left', path: IMAGEPATH+'img22.png'},
  { id: 22, name: 'Bild22', side: 'right', path: IMAGEPATH+'img23.png'},
  { id: 23, name: 'Bild23', side: 'right', path: IMAGEPATH+'img24.png'},
  { id: 24, name: 'Bild24', side: 'left', path: IMAGEPATH+'img26.png'},
  { id: 25, name: 'Bild25', side: 'right', path: IMAGEPATH+'img25.png'},
  { id: 26, name: 'Bild26', side: 'right', path: IMAGEPATH+'img27.png'},
  { id: 27, name: 'Bild27', side: 'right', path: IMAGEPATH+'img28.png'},
  { id: 28, name: 'Bild28', side: 'left', path: IMAGEPATH+'img29.png'},
  { id: 29, name: 'Bild29', side: 'left', path: IMAGEPATH+'img30.png'},
  { id: 30, name: 'Bild30', side: 'right', path: IMAGEPATH+'img31.png'},
  { id: 31, name: 'Bild31', side: 'left', path: IMAGEPATH+'img32.png'},
  { id: 32, name: 'Bild32', side: 'right', path: IMAGEPATH+'img33.png'},
  { id: 33, name: 'Bild33', side: 'left', path: IMAGEPATH+'img34.png'},
  { id: 34, name: 'Bild34', side: 'left', path: IMAGEPATH+'img35.png'},
  { id: 35, name: 'Bild35', side: 'left', path: IMAGEPATH+'img36.png'},
  { id: 36, name: 'Bild36', side: 'right', path: IMAGEPATH+'img37.png'},
  { id: 37, name: 'Bild37', side: 'right', path: IMAGEPATH+'img38.png'},
  { id: 38, name: 'Bild39', side: 'left', path: IMAGEPATH+'img39.png'},
  { id: 39, name: 'Bild40', side: 'left', path: IMAGEPATH+'img40.png'},
  { id: 40, name: 'Bild41', side: 'left', path: IMAGEPATH+'img41.png'},
  { id: 41, name: 'Bild42', side: 'right', path: IMAGEPATH+'img42.png'},
  { id: 42, name: 'Bild43', side: 'left', path: IMAGEPATH+'img43.png'},
  { id: 43, name: 'Bild44', side: 'right', path: IMAGEPATH+'img44.png'},
  { id: 44, name: 'Bild45', side: 'left', path: IMAGEPATH+'img45.png'},
  { id: 45, name: 'Bild46', side: 'right', path: IMAGEPATH+'img46.png'},
  { id: 46, name: 'Bild47', side: 'left', path: IMAGEPATH+'img47.png'},
  { id: 47, name: 'Bild48', side: 'right', path: IMAGEPATH+'img48.png'},
  { id: 48, name: 'Bild49', side: 'left', path: IMAGEPATH+'img49.png'},
  { id: 49, name: 'Bild50', side: 'left', path: IMAGEPATH+'img50.png'},
  { id: 50, name: 'Bild51', side: 'right', path: IMAGEPATH+'img51.png'},
  { id: 51, name: 'Bild52', side: 'right', path: IMAGEPATH+'img52.png'},
  { id: 52, name: 'Bild53', side: 'left', path: IMAGEPATH+'img53.png'},
  { id: 53, name: 'Bild54', side: 'left', path: IMAGEPATH+'img54.png'},
  { id: 54, name: 'Bild55', side: 'right', path: IMAGEPATH+'img55.png'}
];
